Algoritmo "PAR_CONSECUTIVOS"
//LOGICA DE PROGRAMAÇÃO
//ESTRUTURA DE REPETIÇÃO ENQUANTO
// Data atual  : 10/09/2026
Var
   N, I, X: INTEIRO

Inicio
   ESCREVAL("DIGITE UM NUMERO INTEIRO: ")//USUARIO DIGITA
   LEIA(x)

   ENQUANTO X <> 0 FACA

      SE X % 2 <> 0 ENTAO
         X <- X + 1
      FIMSE

      SOMA < - 5 * X + 20
      ESCREVAL("SOMA = ", SOMA)

      ESCREVA("DIGITE UM NUMERO INTEIRO: ")
      LEIA(x)

      FIMENQUANTO4


Fimalgoritmo